// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXq8ruiHOY-PBYGBiF8Hvnm8iFR25o3bA',
    appId: '1:607736027575:web:38363bd014837319f5b032',
    messagingSenderId: '607736027575',
    projectId: 'wildlifealert-24ac5',
    authDomain: 'wildlifealert-24ac5.firebaseapp.com',
    storageBucket: 'wildlifealert-24ac5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbbJrsPpEWdCXaE7K_7tOOtrHFnfCoJsM',
    appId: '1:607736027575:android:17ee947c52b83f8df5b032',
    messagingSenderId: '607736027575',
    projectId: 'wildlifealert-24ac5',
    storageBucket: 'wildlifealert-24ac5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMKLDKtGgxdBWb_GDA67Qo_hyleKLAZro',
    appId: '1:607736027575:ios:00c707290d7326bff5b032',
    messagingSenderId: '607736027575',
    projectId: 'wildlifealert-24ac5',
    storageBucket: 'wildlifealert-24ac5.firebasestorage.app',
    iosBundleId: 'com.example.wildlifeAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMKLDKtGgxdBWb_GDA67Qo_hyleKLAZro',
    appId: '1:607736027575:ios:00c707290d7326bff5b032',
    messagingSenderId: '607736027575',
    projectId: 'wildlifealert-24ac5',
    storageBucket: 'wildlifealert-24ac5.firebasestorage.app',
    iosBundleId: 'com.example.wildlifeAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXq8ruiHOY-PBYGBiF8Hvnm8iFR25o3bA',
    appId: '1:607736027575:web:e35ad77d5686ede3f5b032',
    messagingSenderId: '607736027575',
    projectId: 'wildlifealert-24ac5',
    authDomain: 'wildlifealert-24ac5.firebaseapp.com',
    storageBucket: 'wildlifealert-24ac5.firebasestorage.app',
  );
}
